# Generated by Django 5.0.4 on 2024-06-21 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterMoneyRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('sending_document', models.FileField(blank=True, null=True, upload_to='disaster_Money_sending_documents/')),
                ('money_sending_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('receiving_status', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('region', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('PG_fuel', 'PG_fuel'), ('vehicle_fuel', 'vehicle_fuel'), ('adhoc_man', 'adhoc_man'), ('adhoc_vehicle', 'adhoc_vehicle'), ('others', 'others')], default='None', max_length=100, null=True)),
                ('requisition_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='supporting_document_disaster/')),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, null=True)),
                ('level1_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level2_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level3_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level1_comments', models.TextField(blank=True, null=True)),
                ('level2_comments', models.TextField(blank=True, null=True)),
                ('level3_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('level1_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level2_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level3_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_approval_disaster', to=settings.AUTH_USER_MODEL)),
                ('level2_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level2_approval_disaster', to=settings.AUTH_USER_MODEL)),
                ('level3_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_approval_disaster', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
