# Generated by Django 5.0.4 on 2024-08-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_alter_disastermoneyrequisition_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastermoneyrequisition',
            name='region',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disastermoneyrequisition',
            name='zone',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
    ]
