# Generated by Django 5.0.4 on 2024-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=50)),
                ('zone', models.CharField(choices=[('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=50)),
                ('mp', models.CharField(choices=[('Sylhet', 'Sylhet'), ('Taherpur', 'Taherpur'), ('Sunamganj', 'Sunamganj'), ('Bianibazar', 'Bianaibazar'), ('Dorbhost', 'Dorbhost'), ('Dherai', 'Dherai'), ('Chatak', 'Chatak'), ('Moulovibazar', 'Moulovibazar'), ('Baniachong', 'Baniachong'), ('Juri', 'Juri'), ('Saestaganj', 'Saestaganj'), ('Mymensingh', 'Mymensingh'), ('Fulpur', 'Fulpur'), ('Valuka', 'Valuka'), ('Kisorganj', 'Kisorganj'), ('Netrokona', 'Netrokona'), ('Katiadi', 'Katiadi'), ('Mohonganj', 'Mohonganj'), ('Austogram', 'Austogram'), ('Tangail', 'Tangail'), ('Madhupur', 'Madhupur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Bakshiganj', 'Bakshiganj'), ('Rangpur', 'Rangpur'), ('Hatibandha', 'Hatibandha'), ('Gaibandha', 'Gaibandha'), ('Ulipur', 'Ulipur'), ('Boropar', 'Boropar'), ('Polasbari', 'Polasbari'), ('Dinajpur', 'Dinajpur'), ('Panchghor', 'Panchghor'), ('Jaldhaka', 'Jaldhaka'), ('Thakurgaon', 'Thakurgaon'), ('Rajshahi', 'Rajshahi'), ('Bagura', 'Bagurar'), ('Nachole', 'Nachole'), ('Natore', 'Natore'), ('Chapai', 'Chapai'), ('Bagura', 'Bagura')], max_length=50)),
                ('task_name', models.CharField(blank=True, choices=[('single_phase_meter_change', 'single_phase_meter_change'), ('three_phase_meter_change', 'three_phase_meter_change'), ('5kva_transformer_change', '5kva_transformer_change'), ('10kva_transformer_change', '10kva_transformer_change'), ('transformer_protection', 'transformer_protection'), ('DG_repiar', 'DG_repair')], max_length=200, null=True)),
                ('site_code', models.CharField(blank=True, max_length=50, null=True)),
                ('task_TT_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SOR_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('task_TT_status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], max_length=100, null=True)),
                ('task_completion_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('payment_document', models.ImageField(blank=True, null=True, upload_to='')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('Task_TT_open_date', models.DateField()),
                ('task_TT_close_date', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
