# Generated by Django 5.0.4 on 2024-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0002_alter_civilpower_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilpower',
            old_name='Task_TT_open_date',
            new_name='TT_close_date',
        ),
        migrations.RenameField(
            model_name='civilpower',
            old_name='task_TT_close_date',
            new_name='TT_open_date',
        ),
        migrations.RenameField(
            model_name='civilpower',
            old_name='task_completion_image',
            new_name='requisition_document',
        ),
        migrations.AddField(
            model_name='civilpower',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='task_completion_document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='task_name',
            field=models.CharField(blank=True, choices=[('single_phase_meter_change', 'single_phase_meter_change'), ('three_phase_meter_change', 'three_phase_meter_change'), ('5kva_transformer_change', '5kva_transformer_change'), ('10kva_transformer_change', '10kva_transformer_change'), ('transformer_protection', 'transformer_protection'), ('DG_repiar', 'DG_repair')], max_length=50, null=True),
        ),
    ]
