# Generated by Django 5.0.4 on 2024-07-16 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0003_rename_task_tt_open_date_civilpower_tt_close_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilpower',
            old_name='task_TT_number',
            new_name='TT_number',
        ),
        migrations.RenameField(
            model_name='civilpower',
            old_name='task_TT_status',
            new_name='TT_status',
        ),
        migrations.RenameField(
            model_name='civilpower',
            old_name='cost_amount',
            new_name='approved_amount',
        ),
        migrations.RenameField(
            model_name='civilpower',
            old_name='payment_document',
            new_name='payment_document_image',
        ),
        migrations.RemoveField(
            model_name='civilpower',
            name='mp',
        ),
        migrations.RemoveField(
            model_name='civilpower',
            name='requisition_document',
        ),
        migrations.RemoveField(
            model_name='civilpower',
            name='task_completion_document',
        ),
        migrations.AddField(
            model_name='civilpower',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level1_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level1_approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level1_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_approval_billable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level1_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level2_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level2_approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level2_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level2_approval_billable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level2_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level3_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level3_approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level3_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_approval_billable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='level3_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='requisition_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='requisition_number',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='task_completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='billable_tack_completion_image'),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='civilpower',
            name='work_completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='TT_close_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='TT_open_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
