# Generated by Django 5.0.4 on 2024-07-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0005_remove_civilpower_payment_document_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilpower',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='civil_power_supporting_documents/'),
        ),
    ]
