# Generated by Django 5.0.4 on 2024-07-17 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0006_civilpower_supporting_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilpower',
            name='work_completion_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
