# Generated by Django 5.0.4 on 2024-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0007_alter_civilpower_work_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilpower',
            name='TT_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='work_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
