# Generated by Django 5.0.4 on 2024-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billable', '0013_alter_civilpower_region_alter_civilpower_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilpower',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilpower',
            name='task_name',
            field=models.CharField(blank=True, choices=[('single_phase_meter_change', 'single_phase_meter_change'), ('three_phase_meter_change', 'three_phase_meter_change'), ('5kva_transformer_change', '5kva_transformer_change'), ('10kva_transformer_change', '10kva_transformer_change'), ('transformer_protection', 'transformer_protection'), ('DG_repiar', 'DG_repair'), ('others', 'others')], max_length=50, null=True),
        ),
    ]
