# Generated by Django 5.0.4 on 2024-06-18 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPumpDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True)),
                ('mp', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Taherpur', 'Taherpur'), ('Sunamganj', 'Sunamganj'), ('Bianibazar', 'Bianaibazar'), ('Dorbhost', 'Dorbhost'), ('Dherai', 'Dherai'), ('Chatak', 'Chatak'), ('Moulovibazar', 'Moulovibazar'), ('Baniachong', 'Baniachong'), ('Juri', 'Juri'), ('Saestaganj', 'Saestaganj'), ('Mymensingh', 'Mymensingh'), ('Fulpur', 'Fulpur'), ('Valuka', 'Valuka'), ('Kisorganj', 'Kisorganj'), ('Netrokona', 'Netrokona'), ('Katiadi', 'Katiadi'), ('Mohonganj', 'Mohonganj'), ('Austogram', 'Austogram'), ('Tangail', 'Tangail'), ('Madhupur', 'Madhupur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Bakshiganj', 'Bakshiganj'), ('Rangpur', 'Rangpur'), ('Hatibandha', 'Hatibandha'), ('Gaibandha', 'Gaibandha'), ('Ulipur', 'Ulipur'), ('Boropar', 'Boropar'), ('Polasbari', 'Polasbari'), ('Dinajpur', 'Dinajpur'), ('Panchghor', 'Panchghor'), ('Jaldhaka', 'Jaldhaka'), ('Thakurgaon', 'Thakurgaon'), ('Rajshahi', 'Rajshahi'), ('Bagura', 'Bagurar'), ('Nachole', 'Nachole'), ('Natore', 'Natore'), ('Chapai', 'Chapai'), ('Bagura', 'Bagura')], max_length=100, null=True)),
                ('fuel_pump_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_id', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('fuel_pump_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fuel_pump_address', models.TextField(blank=True, null=True)),
                ('fuel_pump_type', models.CharField(blank=True, choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=100, null=True)),
                ('fuel_pump_supporting_documents', models.FileField(blank=True, null=True, upload_to='fuel_pump_supporting_documents/')),
                ('advance_amount_given', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_period', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PGRdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True)),
                ('mp', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Taherpur', 'Taherpur'), ('Sunamganj', 'Sunamganj'), ('Bianibazar', 'Bianaibazar'), ('Dorbhost', 'Dorbhost'), ('Dherai', 'Dherai'), ('Chatak', 'Chatak'), ('Moulovibazar', 'Moulovibazar'), ('Baniachong', 'Baniachong'), ('Juri', 'Juri'), ('Saestaganj', 'Saestaganj'), ('Mymensingh', 'Mymensingh'), ('Fulpur', 'Fulpur'), ('Valuka', 'Valuka'), ('Kisorganj', 'Kisorganj'), ('Netrokona', 'Netrokona'), ('Katiadi', 'Katiadi'), ('Mohonganj', 'Mohonganj'), ('Austogram', 'Austogram'), ('Tangail', 'Tangail'), ('Madhupur', 'Madhupur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Bakshiganj', 'Bakshiganj'), ('Rangpur', 'Rangpur'), ('Hatibandha', 'Hatibandha'), ('Gaibandha', 'Gaibandha'), ('Ulipur', 'Ulipur'), ('Boropar', 'Boropar'), ('Polasbari', 'Polasbari'), ('Dinajpur', 'Dinajpur'), ('Panchghor', 'Panchghor'), ('Jaldhaka', 'Jaldhaka'), ('Thakurgaon', 'Thakurgaon'), ('Rajshahi', 'Rajshahi'), ('Bagura', 'Bagurar'), ('Nachole', 'Nachole'), ('Natore', 'Natore'), ('Chapai', 'Chapai'), ('Bagura', 'Bagura')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('pgr_id', models.CharField(blank=True, max_length=150, null=True)),
                ('PGR_type', models.CharField(blank=True, choices=[('PGR', 'PGR'), ('PGTL', 'PGTL')], max_length=100, null=True)),
                ('PGR_category', models.CharField(blank=True, choices=[('adhoc', 'adhoc'), ('permanent', 'permanent')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('PGR_photo', models.ImageField(blank=True, null=True, upload_to='PGR_photo')),
                ('PGR_birth_certificate', models.FileField(blank=True, null=True, upload_to='PGR_birth_certificate')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('PGR_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_person_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='fuelPumpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, default=None, null=True)),
                ('payment_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_pay_data', to='common.fuelpumpdatabase')),
            ],
        ),
    ]
