# Generated by Django 5.0.4 on 2024-06-15 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPumpDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_pump_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_id', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('fuel_pump_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fuel_pump_address', models.TextField(blank=True, null=True)),
                ('fuel_pump_type', models.CharField(blank=True, choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=100, null=True)),
                ('fuel_pump_supporting_documents', models.FileField(blank=True, null=True, upload_to='fuel_pump_supporting_documents/')),
                ('advance_amount_given', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_period', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpmp', to='common.mp')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpregion', to='common.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpzone', to='common.zone')),
            ],
        ),
        migrations.CreateModel(
            name='fuelPumpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, default=None, null=True)),
                ('payment_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_pay_data', to='common.fuelpumpdatabase')),
            ],
        ),
    ]
