# Generated by Django 5.0.4 on 2024-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_fuelpumpdatabase_contact_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='contact_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
