# Generated by Django 5.0.4 on 2024-06-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fuelpumpdatabase_fuel_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgrdatabase',
            name='PGR_category',
            field=models.CharField(blank=True, choices=[('adhoc', 'adhoc'), ('permanent', 'permanent')], default='adhoc', max_length=100, null=True),
        ),
    ]
