# Generated by Django 5.0.4 on 2024-06-15 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fuelpumpdatabase_fuelpumppayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pgr_id', models.CharField(blank=True, max_length=150, null=True)),
                ('PGR_type', models.CharField(blank=True, choices=[('PGR', 'PGR'), ('PGTL', 'PGTL')], max_length=100, null=True)),
                ('PGR_category', models.CharField(blank=True, choices=[('adhoc', 'adhoc'), ('permanent', 'permanent')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('PGR_photo', models.ImageField(blank=True, null=True, upload_to='PGR_photo')),
                ('PGR_birth_certificate', models.FileField(blank=True, null=True, upload_to='PGR_birth_certificate')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('PGR_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_person_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_mp', to='common.mp')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_region', to='common.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_zone', to='common.zone')),
            ],
        ),
    ]
