# Generated by Django 5.0.4 on 2024-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_pgrdatabase_pgr_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgrdatabase',
            name='PGR_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgrdatabase',
            name='PGR_payment_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('hourly', 'hourly')], max_length=100, null=True),
        ),
    ]
