# Generated by Django 5.0.4 on 2024-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pgrdatabase_pgr_pay_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpumpdatabase',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'diesel'), ('petrol', 'petrol'), ('octane', 'octane'), ('CNG', 'CNG')], max_length=100, null=True),
        ),
    ]
