# Generated by Django 5.0.4 on 2024-07-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_fuelpumpdatabase_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelpumpdatabase',
            name='fuel_unit_price',
        ),
    ]
