# Generated by Django 5.0.4 on 2024-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_fuelpumpdatabase_fuel_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpumppayment',
            name='payment_document',
            field=models.ImageField(blank=True, null=True, upload_to='fuel_pump_payment'),
        ),
    ]
