# Generated by Django 5.0.4 on 2024-07-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_fuelpumppayment_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgrdatabase',
            name='payment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgrdatabase',
            name='payment_number_choice',
            field=models.CharField(blank=True, choices=[('bikash', 'biksah'), ('nagad', 'nagad'), ('rocket', 'rocket')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgtldatabase',
            name='payment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgtldatabase',
            name='payment_number_choice',
            field=models.CharField(blank=True, choices=[('bikash', 'biksah'), ('nagad', 'nagad'), ('rocket', 'rocket')], default='bikash', max_length=100, null=True),
        ),
    ]
