# Generated by Django 5.0.4 on 2024-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_fuelpumpdatabase_mp_alter_pgrdatabase_mp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrdatabase',
            name='PGR_01hour_rate',
        ),
        migrations.RemoveField(
            model_name='pgrdatabase',
            name='PGR_12hour_rate',
        ),
        migrations.RemoveField(
            model_name='pgrdatabase',
            name='PGR_24hour_rate',
        ),
        migrations.AddField(
            model_name='pgrdatabase',
            name='PGR_contact_hour',
            field=models.CharField(blank=True, choices=[('12hours', '12hours'), ('242hours', '24hours')], max_length=100, null=True),
        ),
    ]
