# Generated by Django 5.0.4 on 2024-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_pgrdatabase_pgr_01hour_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrdatabase',
            name='PGR_contact_hour',
        ),
        migrations.AlterField(
            model_name='pgrdatabase',
            name='PGR_payment_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('hourly', 'hourly'), ('12hours', '12hours'), ('242hours', '24hours')], max_length=100, null=True),
        ),
    ]
