# Generated by Django 5.0.4 on 2024-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_pgrdatabase_pgr_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgrdatabase',
            name='PGR_payment_type',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('hourly', 'hourly'), ('12hours', '12hours'), ('24hours', '24hours')], max_length=100, null=True),
        ),
    ]
