# Generated by Django 5.1.1 on 2024-09-26 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_pgrdatabase_pgr_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True)),
                ('mp', models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Taherpur', 'Taherpur'), ('Sunamganj', 'Sunamganj'), ('Bianibazar', 'Bianaibazar'), ('Dorbhost', 'Dorbhost'), ('Dherai', 'Dherai'), ('Chatak', 'Chatak'), ('Moulovibazar', 'Moulovibazar'), ('Baniachong', 'Baniachong'), ('Juri', 'Juri'), ('Saestaganj', 'Saestaganj'), ('Mymensingh', 'Mymensingh'), ('Fulpur', 'Fulpur'), ('Valuka', 'Valuka'), ('Kisorganj', 'Kisorganj'), ('Netrokona', 'Netrokona'), ('Katiadi', 'Katiadi'), ('Mohonganj', 'Mohonganj'), ('Austogram', 'Austogram'), ('Tangail', 'Tangail'), ('Madhupur', 'Madhupur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Bakshiganj', 'Bakshiganj'), ('Rangpur', 'Rangpur'), ('Hatibandha', 'Hatibandha'), ('Gaibandha', 'Gaibandha'), ('Ulipur', 'Ulipur'), ('Boropar', 'Boropar'), ('Polasbari', 'Polasbari'), ('Dinajpur', 'Dinajpur'), ('Panchghor', 'Panchghor'), ('Jaldhaka', 'Jaldhaka'), ('Thakurgaon', 'Thakurgaon'), ('Rajshahi', 'Rajshahi'), ('Bagura', 'Bagurar'), ('Nachole', 'Nachole'), ('Natore', 'Natore'), ('Chapai', 'Chapai'), ('Bagura', 'Bagura')], max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('CM_user', 'CM_user'), ('PM_user', 'PM_user'), ('others', 'others')], max_length=50, null=True)),
                ('user_designation', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='user_photo')),
                ('user_birth_certificate', models.FileField(blank=True, null=True, upload_to='user_birth_certificate')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('reference_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_person_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
