# Generated by Django 5.1.1 on 2024-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_operationaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaluser',
            name='user_designation',
            field=models.CharField(choices=[('RM', 'RM'), ('ZM', 'ZM'), ('AZM', 'AZM'), ('rectifer_expert', 'rectifier_expert'), ('DGOW_runner', 'DGOW_runner'), ('patroller', 'patroller'), ('AC_IBS', 'AC_IBS'), ('riger', 'riger'), ('RMS_expert', 'RMS_expert'), ('solar_expert', 'solar_expert'), ('ebill', 'ebill'), ('reporter', 'reporter'), ('PM_engineer', 'PM_engineer'), ('PG_technician', 'PG_technician'), ('DG_technician', 'DG_technician'), ('Admin_executive', 'Admin_executive'), ('Account_executive', 'Account_executive'), ('General_staff', 'General_staff')], max_length=50, null=True),
        ),
    ]
