# Generated by Django 5.0.4 on 2024-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='posting_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mp'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.region'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.zone'),
        ),
    ]
