# Generated by Django 5.0.4 on 2024-08-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_resource_num_of_azm_resource_num_of_rm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='num_of_manager',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_of_operational_executive',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_of_other_staff',
        ),
    ]
