# Generated by Django 5.1.1 on 2024-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_resource_mp_alter_resource_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='num_of_admin_account_executive',
            new_name='num_of_account_executive',
        ),
        migrations.AddField(
            model_name='resource',
            name='num_of_admin_executive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
