# Generated by Django 5.0.4 on 2024-06-15 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPumpDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_pump_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_id', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('fuel_pump_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_pump_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fuel_pump_address', models.TextField(blank=True, null=True)),
                ('fuel_pump_type', models.CharField(blank=True, choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=100, null=True)),
                ('fuel_pump_supporting_documents', models.FileField(blank=True, null=True, upload_to='fuel_pump_supporting_documents/')),
                ('advance_amount_given', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_period', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fuelPumpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, default=None, null=True)),
                ('payment_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_pay_data', to='generator.fuelpumpdatabase')),
            ],
        ),
        migrations.AddField(
            model_name='fuelpumpdatabase',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_mp', to='generator.mp'),
        ),
        migrations.CreateModel(
            name='AddPGInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PG_code', models.CharField(default='None', max_length=50)),
                ('PGNumber', models.CharField(default='None', max_length=50)),
                ('PG_brand', models.CharField(choices=[('Honda', 'Honda'), ('Mistsubishi', 'Mistsubishi'), ('wilson', 'wilson'), ('chinese', 'chinese')], default='None', max_length=50)),
                ('PG_serial_number', models.CharField(default='None', max_length=50)),
                ('PG_capacity', models.CharField(choices=[('5kva', '5kva'), ('6kva', '6kva'), ('8kva', '8kva')], default='None', max_length=50)),
                ('PG_supplier', models.CharField(choices=[('vendor1', 'vendor1'), ('vendor2', 'vendor2'), ('vendor3', 'vendor3'), ('own', 'own')], default='None', max_length=50)),
                ('PG_status', models.CharField(blank=True, choices=[('good', 'good'), ('faulty', 'faulty')], max_length=100, null=True)),
                ('PG_purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('PG_hire_date', models.DateField(default=django.utils.timezone.now)),
                ('PG_supporting_documents', models.FileField(blank=True, null=True, upload_to='PG_documents/')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('PG_add_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PGad_admin_user', to=settings.AUTH_USER_MODEL)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_mp', to='generator.mp')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_region', to='generator.region')),
            ],
        ),
        migrations.AddField(
            model_name='fuelpumpdatabase',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_region', to='generator.region'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='generator.region')),
            ],
        ),
        migrations.CreateModel(
            name='PGFuelRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_refill_code', models.CharField(default='None', max_length=50)),
                ('refill_date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'diesel'), ('octane', 'octane'), ('petrol', 'petrol')], default='None', max_length=100, null=True)),
                ('refill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('refill_supporting_documents', models.FileField(blank=True, null=True, upload_to='PG_refill_slips/')),
                ('fuel_supplier_phone', models.CharField(default='None', max_length=50)),
                ('fuel_supplier_address', models.TextField(blank=True, default='None', null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('fuel_pump', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pump_data_info', to='generator.fuelpumpdatabase')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_refill_mp', to='generator.mp')),
                ('pgnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pginfo', to='generator.addpginfo')),
                ('refill_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_refill_requester_name', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_refill_region', to='generator.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_refill_zone', to='generator.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PGFaultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_date', models.DateField(blank=True, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('fault_duration', models.DurationField(blank=True, null=True)),
                ('fault_description', models.TextField(blank=True, max_length=200, null=True)),
                ('fault_type', models.CharField(blank=True, choices=[('air_filter_problem', 'air_filter_problem'), ('oil_filter_problem', 'oil_filter_problem'), ('engine_problem', 'engine_problem'), ('others', 'others')], max_length=200, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('repair_by', models.CharField(blank=True, max_length=100, null=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_fault_mp', to='generator.mp')),
                ('pgnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultinfo', to='generator.addpginfo')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_fault_region', to='generator.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_fault_zone', to='generator.zone')),
            ],
        ),
        migrations.AddField(
            model_name='mp',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mps', to='generator.zone'),
        ),
        migrations.AddField(
            model_name='fuelpumpdatabase',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_zone', to='generator.zone'),
        ),
        migrations.AddField(
            model_name='addpginfo',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_zone', to='generator.zone'),
        ),
    ]
