# Generated by Django 5.0.4 on 2024-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpginfo',
            name='PG_deployment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addpginfo',
            name='fixed_PG_site_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
