# Generated by Django 5.0.4 on 2024-06-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='pgnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgfault', to='generator.addpginfo'),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='pgnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_refill', to='generator.addpginfo'),
        ),
    ]
