# Generated by Django 5.0.4 on 2024-06-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_pgfaultrecord_pgnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgfuelrefill',
            name='mp',
        ),
        migrations.RemoveField(
            model_name='pgfuelrefill',
            name='region',
        ),
        migrations.RemoveField(
            model_name='pgfuelrefill',
            name='zone',
        ),
    ]
