# Generated by Django 5.0.4 on 2024-06-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_addpginfo_pg_deployment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='PG_deployment_type',
            field=models.CharField(blank=True, choices=[('movable', 'movable'), ('fixed', 'fixed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='refill_type',
            field=models.CharField(choices=[('pump', 'pump'), ('local_purchase', 'local Purchase')], default='pump', max_length=20),
        ),
    ]
