# Generated by Django 5.0.4 on 2024-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_addpginfo_pg_deployment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='refill_type',
            field=models.CharField(choices=[('pump', 'pump'), ('local_purchase', 'local_purchase')], default='pump', max_length=20),
        ),
    ]
