# Generated by Django 5.0.4 on 2024-06-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_pgfaultrecord_pgnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgfuelrefill',
            name='mp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilmp', to='generator.mp'),
        ),
        migrations.AddField(
            model_name='pgfuelrefill',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilregion', to='generator.region'),
        ),
        migrations.AddField(
            model_name='pgfuelrefill',
            name='zone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilzone', to='generator.zone'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpmp', to='generator.mp'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpregion', to='generator.region'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpzone', to='generator.zone'),
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultmp', to='generator.mp'),
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultregion', to='generator.region'),
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultzone', to='generator.zone'),
        ),
    ]
