# Generated by Django 5.0.4 on 2024-06-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_pgfuelrefill_mp_pgfuelrefill_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgmp', to='generator.mp'),
        ),
        migrations.AlterField(
            model_name='addpginfo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgregion', to='generator.region'),
        ),
        migrations.AlterField(
            model_name='addpginfo',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgzone', to='generator.zone'),
        ),
    ]
