# Generated by Django 5.0.4 on 2024-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('dailyexpense', '0002_remove_moneyrequisition_mp_and_more'),
        ('generator', '0006_alter_addpginfo_mp_alter_addpginfo_region_and_more'),
        ('tickets', '0002_alter_eticket_mp_alter_eticket_region_and_more'),
        ('vehicle', '0002_remove_addvehicleinfo_vehicle_duty_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgmp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultmp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='mp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilmp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpmp', to='common.mp'),
        ),
        migrations.RemoveField(
            model_name='zone',
            name='region',
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultregion', to='common.region'),
        ),
        migrations.AlterField(
            model_name='addpginfo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgregion', to='common.region'),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilregion', to='common.region'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpregion', to='common.region'),
        ),
        migrations.AlterField(
            model_name='addpginfo',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgzone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='pgfaultrecord',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgfaultzone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='zone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refilzone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='fuelpumpdatabase',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumpzone', to='common.zone'),
        ),
        migrations.DeleteModel(
            name='MP',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
