# Generated by Django 5.0.4 on 2024-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_remove_pgfuelrefill_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgfuelrefill',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'diesel'), ('octane', 'octane'), ('petrol', 'petrol'), ('CNG', 'CNG')], default='None', max_length=100, null=True),
        ),
    ]
