# Generated by Django 5.0.4 on 2024-06-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fuelpumpdatabase_fuelpumppayment'),
        ('generator', '0007_alter_addpginfo_mp_alter_pgfaultrecord_mp_and_more'),
        ('vehicle', '0003_alter_fuelrefill_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='fuel_pump',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pump_data_info', to='common.fuelpumpdatabase'),
        ),
        migrations.RemoveField(
            model_name='fuelpumppayment',
            name='pump',
        ),
        migrations.DeleteModel(
            name='FuelPumpDatabase',
        ),
        migrations.DeleteModel(
            name='fuelPumpPayment',
        ),
    ]
