# Generated by Django 5.0.4 on 2024-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_alter_pgfuelrefill_fuel_pump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgfuelrefill',
            name='fuel_supplier_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
