# Generated by Django 5.0.4 on 2024-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_pgfuelrefill_fuel_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgfuelrefill',
            name='refill_type',
            field=models.CharField(choices=[('pump', 'pump'), ('local_purchase', 'Local Purchase')], default='pump', max_length=20),
        ),
    ]
