# Generated by Django 5.0.4 on 2024-08-24 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_generatorservice_service_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatorservice',
            old_name='total_run_hour_passed',
            new_name='service_hour_passed',
        ),
        migrations.AddField(
            model_name='generatorservice',
            name='total_run_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatorservice',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generatorservice',
            name='date_of_service',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
