# Generated by Django 5.0.4 on 2024-08-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_rename_total_run_hour_passed_generatorservice_service_hour_passed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatorservice',
            old_name='service_hour_passed',
            new_name='last_service_hours',
        ),
        migrations.RemoveField(
            model_name='generatorservice',
            name='total_days_passed',
        ),
        migrations.RemoveField(
            model_name='generatorservice',
            name='total_run_hour',
        ),
    ]
