# Generated by Django 5.0.4 on 2024-08-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_rename_service_hour_passed_generatorservice_last_service_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorservice',
            name='last_service_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
