# Generated by Django 5.0.4 on 2024-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_alter_generatorservice_last_service_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='lub_oil_capacity',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
