# Generated by Django 5.0.4 on 2024-08-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_alter_addpginfo_lub_oil_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatorservice',
            old_name='last_service_hours',
            new_name='service_hours',
        ),
    ]
