# Generated by Django 5.0.4 on 2024-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_rename_last_service_hours_generatorservice_service_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='PG_deployment_type',
            field=models.CharField(blank=True, choices=[('movable_PG', 'movable_PG'), ('fixed_PG', 'fixed_PG'), ('fixed_DG', 'fixed_DG'), ('DGOW', 'DGOW')], max_length=100, null=True),
        ),
    ]
