# Generated by Django 5.0.4 on 2024-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_alter_addpginfo_pg_deployment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='fuel_tank_capacity',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
