# Generated by Django 5.0.4 on 2024-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_alter_addpginfo_fuel_tank_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='fuel_supplier_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='fuel_supplier_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
