# Generated by Django 5.0.4 on 2024-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_alter_pgfuelrefill_fuel_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgfuelrefill',
            name='fuel_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
