# Generated by Django 5.0.4 on 2024-08-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_alter_pgfuelrefill_fuel_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpginfo',
            name='PG_brand',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Mistsubishi', 'Mistsubishi'), ('wilson', 'wilson'), ('chinese', 'chinese'), ('mahindra', 'mahindra')], default='None', max_length=50),
        ),
    ]
