# Generated by Django 5.0.4 on 2024-06-30 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocVehiclePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('adhoc_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('bikash', 'bikash'), ('rocket', 'rocket'), ('nagad', 'nagad'), ('bank_transfer', 'bank_transfer'), ('others', 'others')], max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_supporting_document', models.ImageField(blank=True, null=True, upload_to='adhoc_vehicle_payment')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.addvehicleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdhocVehicleRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('num_of_days_applied', models.IntegerField(blank=True, null=True)),
                ('num_of_days_approved', models.IntegerField(blank=True, null=True)),
                ('requisition_id', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('requisition_date', models.DateField(default=django.utils.timezone.now)),
                ('active_status', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=50)),
                ('level1_approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level2_approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level3_approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level1_comments', models.TextField(blank=True, null=True)),
                ('level2_comments', models.TextField(blank=True, null=True)),
                ('level3_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('level1_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level2_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level3_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_approval_adhocvehicle', to=settings.AUTH_USER_MODEL)),
                ('level2_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level2_approval_adhocvehicle', to=settings.AUTH_USER_MODEL)),
                ('level3_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_approval_adhocvehicle', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhovehicle', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.addvehicleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdhocVehicleAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhoc_in_date', models.DateField(blank=True, null=True)),
                ('adhoc_in_time', models.TimeField(blank=True, null=True)),
                ('adhoc_out_date', models.DateField(blank=True, null=True)),
                ('adhoc_out_time', models.TimeField(blank=True, null=True)),
                ('adhoc_working_hours', models.FloatField(blank=True, null=True)),
                ('adhoc_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adhoc_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.addvehicleinfo')),
                ('adhoc_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_vehicle_payment_ref', to='vehicle.adhocvehiclepayment')),
                ('adhoc_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_vehicle_requisition_ref', to='vehicle.adhocvehiclerequisition')),
            ],
        ),
    ]
