# Generated by Django 5.0.4 on 2024-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicleinfo',
            name='vehicle_rental_type',
            field=models.CharField(blank=True, choices=[('permanent', 'permanent'), ('adhoc', 'adhoc')], default='None', max_length=50, null=True),
        ),
    ]
