# Generated by Django 5.0.4 on 2024-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicleinfo',
            name='vehicle_duty_station',
        ),
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_refill_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_refill_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_refill_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='vehiclefault',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fault_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='vehiclefault',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fault_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='vehiclefault',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fault_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pay_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pay_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pay_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='vehicleruniningdata',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_run_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='vehicleruniningdata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_run_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='vehicleruniningdata',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_run_zone', to='common.zone'),
        ),
    ]
