# Generated by Django 5.0.4 on 2024-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_adhocvehiclepayment_adhocvehiclerequisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrefill',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fuelrefill',
            name='fuel_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('diesel', 'diesel'), ('octane', 'octane'), ('petrol', 'petrol'), ('CNG', 'CNG')], default='None', max_length=100, null=True),
        ),
    ]
