# Generated by Django 5.0.4 on 2024-06-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fuelpumpdatabase_fuelpumppayment'),
        ('vehicle', '0002_remove_addvehicleinfo_vehicle_duty_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrefill',
            name='pump',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_fuel_pump', to='common.fuelpumpdatabase'),
        ),
    ]
