# Generated by Django 5.0.4 on 2024-07-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_fuelrefill_fuel_cost_fuelrefill_fuel_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocvehicleattendance',
            name='vehicle_fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclefault'),
        ),
        migrations.AddField(
            model_name='adhocvehicleattendance',
            name='vehicle_running_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleruniningdata'),
        ),
    ]
