# Generated by Django 5.0.4 on 2024-06-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_fuelrefill_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrefill',
            name='refill_type',
            field=models.CharField(choices=[('pump', 'pump'), ('local_purchase', 'Local Purchase')], default='pump', max_length=20),
        ),
    ]
