# Generated by Django 5.0.4 on 2024-06-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_fuelrefill_refill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrefill',
            name='fuel_supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
