# Generated by Django 5.0.4 on 2024-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_rename_adhoc_bill_amount_adhocvehicleattendance_adhoc_total_bill_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvehicleinfo',
            old_name='vehicle_money_commit_per_kilometer',
            new_name='vehicle_max_kilometer_CNG',
        ),
        migrations.RenameField(
            model_name='adhocvehicleattendance',
            old_name='adhoc_pay_rate',
            new_name='adhoc_vehicle_base_bill_amount',
        ),
        migrations.RenameField(
            model_name='adhocvehicleattendance',
            old_name='adhoc_total_bill_amount',
            new_name='adhoc_vehicle_overtime_bill_amount',
        ),
        migrations.RenameField(
            model_name='adhocvehicleattendance',
            old_name='adhoc_vehicle_bill_amount',
            new_name='adhoc_vehicle_total_bill_amount',
        ),
        migrations.RemoveField(
            model_name='adhocvehicleattendance',
            name='adhoc_kilometer_run',
        ),
        migrations.RemoveField(
            model_name='adhocvehicleattendance',
            name='kilometer_cost',
        ),
        migrations.AddField(
            model_name='addvehicleinfo',
            name='vehicle_hour_contact',
            field=models.CharField(blank=True, choices=[('12 hours', '12 hour'), ('24 hours', '24 hours')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addvehicleinfo',
            name='vehicle_money_commit_per_kilometer_CNG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addvehicleinfo',
            name='vehicle_money_commit_per_kilometer_gasoline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='day_end_kilometer_cost_CNG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='day_end_kilometer_cost_gasoline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='day_end_kilometer_run',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
