# Generated by Django 5.0.4 on 2024-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_rename_vehicle_money_commit_per_kilometer_addvehicleinfo_vehicle_max_kilometer_cng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='total_kilomter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
