# Generated by Django 5.0.4 on 2024-08-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehicleruniningdata_total_kilomter_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleruniningdata',
            old_name='total_kilomter_cost',
            new_name='total_kilometer_cost',
        ),
    ]
