# Generated by Django 5.0.4 on 2024-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_rename_total_kilomter_cost_vehicleruniningdata_total_kilometer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='comments',
            field=models.TextField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_body_overtime_paid',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_driver_overtime_paid',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_rent_paid',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
