# Generated by Django 5.0.4 on 2024-08-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_vehiclerentalcost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelrefill',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclefault',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclefault',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleruniningdata',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleruniningdata',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
    ]
