# Generated by Django 5.0.4 on 2024-08-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_addvehicleinfo_mp_alter_fuelrefill_mp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocvehiclerequisition',
            name='num_of_days_approved',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
