# Generated by Django 5.0.4 on 2024-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_alter_adhocvehiclerequisition_num_of_days_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocvehiclerequisition',
            name='num_of_days_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
