# Generated by Django 5.0.4 on 2024-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_alter_adhocvehiclerequisition_num_of_days_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocvehicleattendance',
            old_name='adhoc_requisition',
            new_name='adhoc_requisition_vehicle',
        ),
    ]
