# Generated by Django 5.0.4 on 2024-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_rename_adhoc_requisition_adhocvehicleattendance_adhoc_requisition_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicleinfo',
            name='vehicle_operational_mode',
            field=models.CharField(choices=[('CM_vehicle', 'CM_vehicle'), ('PM_vehicle', 'PM_vehicle'), ('others', 'others')], default='None', max_length=50),
        ),
    ]
