# Generated by Django 5.0.4 on 2024-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_alter_addvehicleinfo_vehicle_operational_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerentalcost',
            name='vehicle_kilometer_paid',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalcost',
            name='vehicle_total_paid',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
