# Generated by Django 5.0.4 on 2024-08-31 06:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_vehiclerentalcost_vehicle_body_overtime_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_body_overtime_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_driver_overtime_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_kilometer_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_rent_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerentalcost',
            name='vehicle_total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
    ]
