# Generated by Django 5.0.4 on 2024-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_alter_vehiclerentalcost_vehicle_body_overtime_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocvehicleattendance',
            name='adhoc_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
