# Generated by Django 5.0.4 on 2024-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_adhocvehicleattendance_adhoc_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='weekend_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
