# Generated by Django 5.0.4 on 2024-09-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_vehicleruniningdata_weekend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleruniningdata',
            name='vehicle_rent_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
