# Generated by Django 5.0.4 on 2024-09-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_vehicleruniningdata_vehicle_rent_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicleinfo',
            name='vehicle_rent_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
