# Generated by Django 5.0.4 on 2024-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='purpose',
            field=models.CharField(choices=[('local_conveyance', 'local_conveyance'), ('pg_carrying_cost', 'pg_carrying-cost'), ('night_bill', 'night_bill'), ('pg_local_fuel_purchase', 'pg_local_fuel_purchase'), ('vehicle_local_fuel_purchase', 'vehicle_local_fuel_purchase'), ('toll', 'toll'), ('food', 'food'), ('item_purchase', 'item_purchase'), ('field_advance', 'field_advance'), ('others', 'others')], max_length=100),
        ),
    ]
