# Generated by Django 5.0.4 on 2024-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('dailyexpense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequisition',
            name='mp',
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_req_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_req_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expense_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expense_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expense_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='summaryexpenses',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sum_expense_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='summaryexpenses',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sum_expense_zone', to='common.zone'),
        ),
    ]
