# Generated by Django 5.0.4 on 2024-08-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0005_alter_moneyrequisition_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summaryexpenses',
            name='region',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summaryexpenses',
            name='zone',
            field=models.CharField(blank=True, choices=[('', ''), ('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True),
        ),
    ]
