# Generated by Django 5.1.1 on 2024-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0010_dailyexpenserequisition_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenserequisition',
            name='purpose_civil_power',
            field=models.CharField(choices=[('single_phase_meter', 'single_phase_meter'), ('three_phase_meter', 'three_phase_meter'), ('5kva_transformer', '5kva_transformer'), ('10kva_transformer', '10kva_transformer'), ('security_protection', 'security_protection'), ('conveyance', 'conveyance'), ('food', 'food'), ('DA', 'DA'), ('hotel_bill', 'hotel_bill'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='purpose',
            field=models.CharField(choices=[('local_conveyance', 'local_conveyance'), ('long_distance_transport', 'long_distance_transport'), ('pg_carrying_cost', 'pg_carrying-cost'), ('night_bill', 'night_bill'), ('pg_local_fuel_purchase', 'pg_local_fuel_purchase'), ('vehicle_local_fuel_purchase', 'vehicle_local_fuel_purchase'), ('toll', 'toll'), ('food', 'food'), ('item_purchase', 'item_purchase'), ('field_advance', 'field_advance'), ('DA', 'DA'), ('hotel_bill', 'hotel_bill'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Adhoc_man', 'Adhoc_man'), ('Adhoc_vehicle', 'Adhoc_vehicle'), ('Civil_power', 'Civil_power')], default='None', max_length=100, null=True),
        ),
    ]
