# Generated by Django 5.1.1 on 2024-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0011_dailyexpenserequisition_purpose_civil_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='work_type',
            field=models.CharField(choices=[('CM_work', 'CM_work'), ('PM_work', 'PM_work'), ('Civil_power', 'Civil_power'), ('disaster_support', 'disaster_support')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequisition',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Adhoc_man', 'Adhoc_man'), ('Adhoc_vehicle', 'Adhoc_vehicle'), ('Civil_power', 'Civil_power'), ('disaster', 'disaster')], default='None', max_length=100, null=True),
        ),
    ]
