# Generated by Django 5.1.1 on 2024-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0012_alter_dailyexpenserequisition_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='purpose_civil_power',
            field=models.CharField(blank=True, choices=[('single_phase_meter', 'single_phase_meter'), ('three_phase_meter', 'three_phase_meter'), ('5kva_transformer', '5kva_transformer'), ('10kva_transformer', '10kva_transformer'), ('security_protection', 'security_protection'), ('conveyance', 'conveyance'), ('food', 'food'), ('DA', 'DA'), ('hotel_bill', 'hotel_bill'), ('others', 'others')], max_length=100, null=True),
        ),
    ]
