# Generated by Django 5.1.1 on 2024-09-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_operationaluser_user_designation'),
        ('dailyexpense', '0013_alter_dailyexpenserequisition_purpose_civil_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenserequisition',
            name='pgtl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgtl_expense', to='common.pgtldatabase'),
        ),
        migrations.AddField(
            model_name='dailyexpenserequisition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_user_ref', to='common.operationaluser'),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='user_type',
            field=models.CharField(choices=[('CM_user', 'CM_user'), ('PM_user', 'PM_user'), ('general_user', 'general_user'), ('team_leader', 'team_leader')], max_length=50, null=True),
        ),
    ]
