# Generated by Django 5.1.1 on 2024-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0014_dailyexpenserequisition_pgtl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='level1_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='level2_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='level3_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='purpose',
            field=models.CharField(blank=True, choices=[('local_conveyance', 'local_conveyance'), ('long_distance_transport', 'long_distance_transport'), ('pg_carrying_cost', 'pg_carrying-cost'), ('night_bill', 'night_bill'), ('pg_local_fuel_purchase', 'pg_local_fuel_purchase'), ('vehicle_local_fuel_purchase', 'vehicle_local_fuel_purchase'), ('toll', 'toll'), ('food', 'food'), ('item_purchase', 'item_purchase'), ('field_advance', 'field_advance'), ('DA', 'DA'), ('hotel_bill', 'hotel_bill'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CM_user', 'CM_user'), ('PM_user', 'PM_user'), ('general_user', 'general_user'), ('team_leader', 'team_leader')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpenserequisition',
            name='work_type',
            field=models.CharField(blank=True, choices=[('CM_work', 'CM_work'), ('PM_work', 'PM_work'), ('Civil_power', 'Civil_power'), ('disaster_support', 'disaster_support')], max_length=50, null=True),
        ),
    ]
