# Generated by Django 5.0.4 on 2024-06-18 05:26

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('generator', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='eTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Moulovibazar', 'Moulovibazar'), ('Mymensingh', 'Mymensingh'), ('Kisorganj', 'Kisorganj'), ('Tangail', 'Tangail'), ('Rangpur', 'Rangpur'), ('Dinajpur', 'Dinajpur'), ('Bagura', 'Bagura'), ('Rajshahi', 'Rajshahi')], max_length=100, null=True)),
                ('mp', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Taherpur', 'Taherpur'), ('Sunamganj', 'Sunamganj'), ('Bianibazar', 'Bianaibazar'), ('Dorbhost', 'Dorbhost'), ('Dherai', 'Dherai'), ('Chatak', 'Chatak'), ('Moulovibazar', 'Moulovibazar'), ('Baniachong', 'Baniachong'), ('Juri', 'Juri'), ('Saestaganj', 'Saestaganj'), ('Mymensingh', 'Mymensingh'), ('Fulpur', 'Fulpur'), ('Valuka', 'Valuka'), ('Kisorganj', 'Kisorganj'), ('Netrokona', 'Netrokona'), ('Katiadi', 'Katiadi'), ('Mohonganj', 'Mohonganj'), ('Austogram', 'Austogram'), ('Tangail', 'Tangail'), ('Madhupur', 'Madhupur'), ('Jamalpur', 'Jamalpur'), ('Sherpur', 'Sherpur'), ('Bakshiganj', 'Bakshiganj'), ('Rangpur', 'Rangpur'), ('Hatibandha', 'Hatibandha'), ('Gaibandha', 'Gaibandha'), ('Ulipur', 'Ulipur'), ('Boropar', 'Boropar'), ('Polasbari', 'Polasbari'), ('Dinajpur', 'Dinajpur'), ('Panchghor', 'Panchghor'), ('Jaldhaka', 'Jaldhaka'), ('Thakurgaon', 'Thakurgaon'), ('Rajshahi', 'Rajshahi'), ('Bagura', 'Bagurar'), ('Nachole', 'Nachole'), ('Natore', 'Natore'), ('Chapai', 'Chapai'), ('Bagura', 'Bagura')], max_length=100, null=True)),
                ('internal_ticket_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, choices=[('Edotco', 'Edotco'), ('GP', 'GP'), ('BanglaLink', 'Banglalink'), ('Robi', 'Robi'), ('Teletalk', 'Teletalk'), ('emergency_support', 'emergency_support')], default='None', max_length=50, null=True)),
                ('customer_ticket_ref', models.CharField(max_length=50)),
                ('site_id', models.CharField(max_length=50)),
                ('ticket_origin_date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_origin_time', models.TimeField(default=tickets.models.get_current_time)),
                ('assigned_vehicle_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Adhoc', 'Adhoc')], max_length=20)),
                ('internal_generator_running_hours', models.DurationField(blank=True, null=True)),
                ('internal_calculated_fuel_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_generator_running_hours', models.DurationField(blank=True, null=True)),
                ('customer_calculated_fuel_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ticket_status', models.CharField(blank=True, choices=[('open', 'open'), ('running', 'running'), ('onTheWay', 'onTheWay'), ('TT_Miss', 'TT_Miss'), ('TT_Valid', 'TT_Valid'), ('TT_connected', 'TT_connected'), ('team_assign', 'team_assign'), ('TT_invalid', 'TT_invalid')], default='open', max_length=100, null=True)),
                ('fuel_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_PGR', to='common.pgrdatabase')),
                ('pg_fuel_refill', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_fuel', to='generator.pgfuelrefill')),
                ('pgnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtickets', to='generator.addpginfo')),
                ('team_leader_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_PGTL', to='common.pgrdatabase')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.addvehicleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ChildTicketExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_external_ticket_number', models.CharField(max_length=50)),
                ('child_external_generator_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_external_generator_start_time', models.TimeField(blank=True, null=True)),
                ('child_external_generator_stop_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_external_generator_stop_time', models.TimeField(blank=True, null=True)),
                ('child_external_generator_running_hours', models.DurationField(blank=True, null=True)),
                ('child_external_calculated_fuel_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_external_tt_image', models.ImageField(blank=True, null=True, upload_to='child_tt_image_external/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tickets_external', to='tickets.eticket')),
            ],
        ),
        migrations.CreateModel(
            name='ChildTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_ticket_number', models.CharField(max_length=50)),
                ('child_internal_generator_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_internal_generator_start_time', models.TimeField(blank=True, null=True)),
                ('child_internal_generator_stop_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_internal_generator_stop_time', models.TimeField(blank=True, null=True)),
                ('child_internal_generator_running_hours', models.DurationField(blank=True, null=True)),
                ('child_internal_calculated_fuel_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_tt_image', models.ImageField(blank=True, null=True, upload_to='child_tt_image/')),
                ('child_external_generator_start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_external_generator_start_time', models.TimeField(blank=True, null=True)),
                ('child_external_generator_stop_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('child_external_generator_stop_time', models.TimeField(blank=True, null=True)),
                ('child_external_generator_running_hours', models.DurationField(blank=True, null=True)),
                ('child_external_calculated_fuel_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tickets', to='tickets.eticket')),
            ],
        ),
    ]
