# Generated by Django 5.0.4 on 2024-06-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticket',
            name='assigned_vehicle_type',
        ),
    ]
