# Generated by Django 5.0.4 on 2024-06-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_zone', to='common.zone'),
        ),
        migrations.AlterField(
            model_name='pgrdatabase',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_mp', to='common.mp'),
        ),
        migrations.AlterField(
            model_name='pgrdatabase',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_region', to='common.region'),
        ),
        migrations.AlterField(
            model_name='pgrdatabase',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgr_zone', to='common.zone'),
        ),
    ]
