# Generated by Django 5.0.4 on 2024-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('disaster_support', 'disaster_support')], max_length=100, null=True),
        ),
    ]
