# Generated by Django 5.0.4 on 2024-06-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_pgrdatabase'),
        ('tickets', '0002_alter_eticket_mp_alter_eticket_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='team_leader_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_PGTL', to='common.pgrdatabase'),
        ),
        migrations.AlterField(
            model_name='eticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_PGR', to='common.pgrdatabase'),
        ),
        migrations.DeleteModel(
            name='PGRdatabase',
        ),
    ]
