# Generated by Django 5.0.4 on 2024-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_eticket_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
