# Generated by Django 5.0.4 on 2024-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_chatmessage_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
