# Generated by Django 5.0.4 on 2024-06-24 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_pgrdatabase_pgr_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhoc_in_date', models.DateField(blank=True, null=True)),
                ('adhoc_in_time', models.TimeField(blank=True, null=True)),
                ('adhoc_out_date', models.DateField(blank=True, null=True)),
                ('adhoc_out_time', models.TimeField(blank=True, null=True)),
                ('adhoc_working_hours', models.DurationField(blank=True, null=True)),
                ('adhoc_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adhoc_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pgrdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='AdhocPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('adhoc_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('bikash', 'bikash'), ('rocket', 'rocket'), ('nagad', 'nagad'), ('bank_transfer', 'bank_transfer')], max_length=100, null=True)),
                ('pyament_supporting_document', models.ImageField(blank=True, null=True, upload_to='adhoc_payment')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.pgrdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='AdhocRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_days', models.IntegerField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('requisition_date', models.DateField(default=django.utils.timezone.now)),
                ('active_status', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('level1_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level2_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level3_approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
                ('level1_comments', models.TextField(blank=True, null=True)),
                ('level2_comments', models.TextField(blank=True, null=True)),
                ('level3_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('level1_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level2_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level3_approval_date', models.DateTimeField(blank=True, null=True)),
                ('level1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_approval_adhocman', to=settings.AUTH_USER_MODEL)),
                ('level2_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level2_approval_adhocman', to=settings.AUTH_USER_MODEL)),
                ('level3_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level3_approval_adhocman', to=settings.AUTH_USER_MODEL)),
                ('pgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pgrdatabase')),
            ],
        ),
    ]
