# Generated by Django 5.0.4 on 2024-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0001_initial'),
        ('common', '0003_alter_pgrdatabase_pgr_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocrequisition',
            name='pgr',
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='pgr',
            field=models.ManyToManyField(blank=True, null=True, to='common.pgrdatabase'),
        ),
    ]
