# Generated by Django 5.0.4 on 2024-06-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0002_remove_adhocrequisition_pgr_adhocrequisition_pgr'),
        ('common', '0003_alter_pgrdatabase_pgr_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocrequisition',
            name='pgr',
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='pgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.pgrdatabase'),
        ),
    ]
