# Generated by Django 5.0.4 on 2024-06-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0003_remove_adhocrequisition_pgr_adhocrequisition_pgr'),
        ('tickets', '0002_eticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocrequisition',
            name='purpose',
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='site_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.eticket'),
        ),
    ]
