# Generated by Django 5.0.4 on 2024-06-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0004_remove_adhocrequisition_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocrequisition',
            name='site_code',
        ),
    ]
