# Generated by Django 5.0.4 on 2024-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0005_remove_adhocrequisition_site_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocrequisition',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
