# Generated by Django 5.0.4 on 2024-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0006_adhocrequisition_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocrequisition',
            old_name='num_of_days',
            new_name='num_of_days_applied',
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='num_of_days_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='requisition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
