# Generated by Django 5.0.4 on 2024-06-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0007_rename_num_of_days_adhocrequisition_num_of_days_applied_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocrequisition',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhocman', to=settings.AUTH_USER_MODEL),
        ),
    ]
