# Generated by Django 5.0.4 on 2024-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0008_adhocrequisition_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='requisition_id',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
