# Generated by Django 5.0.4 on 2024-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0009_alter_adhocrequisition_requisition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='level1_approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='level2_approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='level3_approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
    ]
