# Generated by Django 5.0.4 on 2024-06-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0010_alter_adhocrequisition_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocattendance',
            name='adhoc_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_payment', to='adhocman.adhocpayment'),
        ),
    ]
