# Generated by Django 5.0.4 on 2024-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0011_adhocattendance_adhoc_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
