# Generated by Django 5.0.4 on 2024-06-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0012_adhocpayment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocpayment',
            old_name='pyament_supporting_document',
            new_name='payment_supporting_document',
        ),
    ]
