# Generated by Django 5.0.4 on 2024-06-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0013_rename_pyament_supporting_document_adhocpayment_payment_supporting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocattendance',
            name='adhoc_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_payment_ref', to='adhocman.adhocpayment'),
        ),
    ]
