# Generated by Django 5.0.4 on 2024-06-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0015_rename_adhoc_payment_adhocattendance_adhoc_payment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocattendance',
            old_name='adhoc_payment_data',
            new_name='adhoc_payment',
        ),
    ]
