# Generated by Django 5.0.4 on 2024-06-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0016_rename_adhoc_payment_data_adhocattendance_adhoc_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocattendance',
            name='adhoc_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_requisition_ref', to='adhocman.adhocrequisition'),
        ),
    ]
