# Generated by Django 5.0.4 on 2024-06-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0017_adhocattendance_adhoc_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocrequisition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocrequisition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
