# Generated by Django 5.0.4 on 2024-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0018_adhocrequisition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocattendance',
            name='adhoc_working_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocrequisition',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
