# Generated by Django 5.0.4 on 2024-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0021_alter_adhocpayment_payment_supporting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocrequisition',
            name='requisition_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('expire', 'expire')], max_length=20, null=True),
        ),
    ]
