# Generated by Django 5.0.4 on 2024-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0022_adhocrequisition_requisition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='requisition_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('expire', 'expire')], default='active', max_length=20, null=True),
        ),
    ]
