# Generated by Django 5.0.4 on 2024-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0023_alter_adhocrequisition_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocattendance',
            name='adhoc_net_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
