# Generated by Django 5.0.4 on 2024-07-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0024_adhocattendance_adhoc_net_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocattendance',
            name='adhoc_net_payment',
        ),
    ]
