# Generated by Django 5.0.4 on 2024-07-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0026_adhocattendance_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocattendance',
            old_name='ticket',
            new_name='adhoc_ticket',
        ),
    ]
