# Generated by Django 5.0.4 on 2024-07-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0027_rename_ticket_adhocattendance_adhoc_ticket'),
        ('tickets', '0003_alter_eticket_mp_alter_eticket_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocattendance',
            name='adhoc_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_ticket_runhour', to='tickets.eticket'),
        ),
    ]
