# Generated by Django 5.0.4 on 2024-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0029_alter_adhocattendance_adhoc_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='num_of_days_approved',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
