# Generated by Django 5.0.4 on 2024-08-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0030_alter_adhocrequisition_num_of_days_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocrequisition',
            name='num_of_days_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
