# Generated by Django 5.0.4 on 2024-08-22 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0031_alter_adhocrequisition_num_of_days_approved'),
        ('common', '0018_remove_pgrdatabase_pgr_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdhocRequisition',
            new_name='AdhocManRequisition',
        ),
    ]
