# Generated by Django 5.0.4 on 2024-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhocman', '0032_rename_adhocrequisition_adhocmanrequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocattendance',
            name='adhoc_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
